OPENSHIFT_VERSION=5.0
IMAGE_FROM=registry.ci.openshift.org/coreos/rhel-coreos-base:10.2

# Used by the generate-labels script
IMAGE_NAME=openshift/ose-rhel-coreos-10
IMAGE_CPE=cpe:/a:redhat:openshift:5.0::el10
