OPENSHIFT_VERSION=5.0
IMAGE_FROM=registry.ci.openshift.org/coreos/stream-coreos-base:10

# SCOS/OKD: no labels.json or OCI labels for name/cpe (so don't define them)
# IMAGE_NAME=
# IMAGE_CPE=

# The names of the yum repos to use for the node image build.
# XXX: use of the rhel-*server-ose-* ART repo shouldn't happen for OKD; see related XXX
#      in build-node-image.sh. Also we must put the ART repo last for the modification
#      in the script to work.
YUM_REPO_NAMES=c10s-baseos,c10s-appstream,c10s-sig-nfv,c10s-sig-cloud-okd,rhel-10.2-server-ose-5.0
